config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #got an error when I changed categories#something -> categories#something
  
  root 'home#index'

  resources :categories do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, uniqueness: true, length: { maximum: 20}
  validates :details, presence: true, length: { minimum: 5 }

  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end

  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  private

  def category_params
    params.require(:category).permit(:name, :details) # confused if :article should always be used  
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end

  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  private

  def category_params
    params.require(:category).permit(:name, :details) # confused if :article should always be used  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category

  def index
    @tasks = @category.tasks
  end

  def new 
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.category_id = params[:id]
    if @task.save
      redirect_to category_tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to categories_path
    else
      render :edit
    end

  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    @task.save

    redirect_to category_tasks_path
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<%= form_with scope: :category, model: @category , locale: true do |f| %>

  <div>
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', categories_path, class: 'btn btn-outline-primary btn-sm', method: :get %>

app/views/categories/index.html.erb
<div class='main'>
  <div class='container'>
    <% @categories.each do | category | %>
      <div class="card" style="width: 17.5rem;">
        <div class="card-img-top"> 
          <h6> <%= category.created_at.try(:to_date) %> </h6>
          <h4> <%= category.name %> </h4>
          <p> <%= category.details %> </p>
        </div>

        <div class="card-btn">
          <h2> <%= link_to 'View', category_path(category.id), class: 'btn btn-outline-light btn-sm', method: :get%> </h2>
          <h2> <%= link_to 'Edit', edit_category_path(category.id), class: 'btn btn-outline-light btn-sm', method: :get%> </h2>

          <h2> <%= link_to 'Add Task', new_category_task_path(category.id), class: 'btn btn-outline-light btn-sm', method: :get%> </h2>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Add Category', new_category_path, class: 'btn btn-outline-light btn-lg', method: :get%>
</div>

app/views/categories/new.html.erb
<%= form_with scope: :category, model: @category, locale: true do |f| %>

  <div class="mb-3">
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="mb-3">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-outline-primary btn-sm' %>
  </div>

<% end %>

<%= link_to 'Back', categories_path, class: 'btn btn-outline-primary btn-lg', method: :get %>

app/views/categories/show.html.erb
<div  class='card-shown'>
  <div class="card-img-top shown">
    <h6> <%= @category.created_at.try(:to_date) %> </h6>
    <h1> <%= @category.name %></h1>
    <p> <%= @category.details %></p>
  </div>

  <div class='card-btn'>
    <%= link_to 'Back', categories_path, class: 'btn btn-outline-primary btn-md', method: :get %>
  </div>
</div> 

app/views/categories/update.html.erb
<%= form_with scope: :category, model: @category, method: :post, locale: true do |f| %>

  <div>
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/category/edit.html.erb
<%= form_with scope: :category, url: category_update_path, locale: true do |f| %>

  <div>
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/category/new.html.erb
<%= form_with scope: :article, url: category_create_path, locale: true do |f| %>

  <div>
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/category/update,.html.erb
<%= form_with scope: :category, url: category_update_path, locale: true do |f| %>

  <div>
    <% if @category.errors.any? %>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/home/index.html.erb
<%= link_to 'Categories', categories_path, class: 'btn btn-outline-primary btn-md', method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with scope: :task, model: @task , locale: true do |f| %>

  <div>
    <% if @task.errors.any? %>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', categories_tasks_path, class: 'btn btn-outline-primary btn-sm', method: :get %>

app/views/tasks/index.html.erb
<div class='main'>
    <% @tasks.each do | task | %>
      <div class="sub">
        <p> <%= task.created_at.try(:to_date) %> </p>
        <p> <%= task.category_id %> </p>
        <p> <%= task.body %> </p>

        <%= link_to 'Edit', edit_category_task_path(task.id)/edit, class: 'btn btn-outline-primary btn-sm', method: :get%>
        <%= link_to 'Delete', category_tasks_path(task.id), class: 'btn btn-outline-primary btn-sm', method: :delete%>

        </div>
    <% end %>
</div>

<%= link_to 'Add task', new_category_task_path, class: 'btn btn-outline-primary btn-lg', method: :get%>

app/views/tasks/new.html.erb
<%= form_with scope: :task, model: @tasks, locale: true do |f| %>

  <div class="mb-3">
    <% if @task.errors.any? %>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-outline-primary btn-sm' %>
  </div>

<% end %>

<%= link_to 'Back', category_tasks_path, class: 'btn btn-outline-primary btn-lg', method: :get %>

app/views/tasks/show.html.erb
<div>
  <div>
    <p> <%= @task.created_at.try(:to_date) %> </p>
    <p> <%= @task.body %></p>
  </div>

  <%= link_to 'Back', category_tasks_path, class: 'btn btn-outline-primary btn-sm', method: :get %>
</div> 

app/views/tasks/update.html.erb
<%= form_with scope: :task, model: @task , locale: true do |f| %>

  <div>
    <% if @task.errors.any? %>
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', categories_tasks_path, class: 'btn btn-outline-primary btn-sm', method: :get %>